backend:
  name: github
  repo: open-innovations/yff-wireframe
  branch: main
locale: en-GB
media_folder: src/images/uploads
collections:
  - name: report
    label: Report
    extension: yml
    folder: src/_data/reports/
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publication Date
        widget: datetime
        format: YYYY-MM-DD
        date_format: D MMM YYYY
        time_format: false
        picker_utc: true
      - name: summary
        label: Summary
        widget: markdown
      - name: sections
        label: Sections
        widget: list
        collapsed: true
        summary: '{{fields.title}}'
        fields:
          - name: title
            label: Section Title
            widget: string
          - name: summary
            label: Section Summary
            widget: markdown
          - name: topics
            label: Section Topics
            widget: categories
          - name: blocks
            label: Section Blocks
            widget: list
            summary: '{{fields.title}}'
            fields:
              - name: title
                label: Block Title
                type: string
              - name: summary
                type: text
site_url: 'https://open-innovations.github.io/yff-wireframe/'
local_backend: false
